imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    filters:
        less:
            apply_to: "\.less$"
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
        cssrewrite: ~

braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
    less_filter: less
    customize:
        variables_file: %kernel.root_dir%/Resources/less/variables.less



# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User

knp_gaufrette:
    adapters:
        local_content_adapter:
            local:
                directory:  %kernel.root_dir%/Resources/content/
                create:     true
        local_resource_adapter:
            local:
                directory:  %kernel.root_dir%/../web/resources/
                create:     true


    filesystems:
        local_content:
            adapter:    local_content_adapter
            alias:      local_content_fs
        local_resource:
            adapter:    local_resource_adapter
            alias:      local_resource_fs



knp_markdown:
    parser:
        service: cms.service.markdown

doctrine_cache:
    providers:
        page_cache:
            type: file_system
            #extension: cache
            #directory: %kernel.rootdir%/