parameters:
  lender.class: AppBundle\Entity\Credit\Lender
  agreement.class: AppBundle\Entity\Credit\Agreement

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: app_main } # The alias is what is used to retrieve the menu

    app.controller.static:
        class:    AppBundle\Controller\StaticController
        arguments:
            - @app.controller_utils
            - @local_content_fs
            - @app.repository.lender
            - @app.repository.agreement

    app.controller.lender:
        class:    AppBundle\Controller\LenderController
        arguments:
            - @app.controller_utils
            - @app.repository.lender

    app.controller.agreement:
        class:    AppBundle\Controller\AgreementController
        arguments:
            - @app.controller_utils
            - @app.repository.agreement


    app.repository.lender:
        class: %lender.class%Repository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [%lender.class%]

    app.repository.agreement:
        class: %agreement.class%Repository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [%agreement.class%]

    app.form.credit.lendertype:
        class: AppBundle\Form\Credit\LenderType
        tags:
            - { name: form.type, alias: credit_lender }

    app.form.credit.agreementtype:
        class: AppBundle\Form\Credit\AgreementType
        tags:
            - { name: form.type, alias: credit_agreement}


    app.form..idtype:
        class: AppBundle\Form\IdInterfaceType
        tags:
            - { name: form.type, alias: id }

    app.form.general.personnametype:
        class: AppBundle\Form\General\PersonNameType
        tags:
            - { name: form.type, alias: personname}

    app.form.general.postaladdresstype:
        class: AppBundle\Form\General\PostalAddressType
        tags:
            - { name: form.type, alias: postaladdress}

    app.controller_utils:
        class:      AppBundle\Service\ControllerUtils
        lazy:       true
        arguments:  [@templating, @router, @form.factory, @security.context, @app.service.unsafeactionform]

    security.context:
        class:      %security.context.class%
        lazy:       true
        arguments:  [@security.token_storage, @security.authorization_checker]

    form.factory:
        class:      %form.factory.class%
        lazy:       true
        arguments:  [@form.registry, @form.resolved_type_factory]

    app.twig.unsafeactionextension:
        class:      AppBundle\Twig\UnsafeActionExtension
        arguments:  [ @app.service.unsafeactionform, @twig.form.renderer ]
        tags:       [ { name: twig.extension } ]

    app.service.unsafeactionform:
        class:      AppBundle\Service\UnsafeActionFormBuilder
        arguments:  [ @form.factory]
